### ISSUE TITLE
maven not building for project

### ISSUE THREAD

**Issue by dtracers** [pjklauser/protobuf-rpc-pro#39]
Hi I am currently using a tool to build the protobuf straight from github.

Here is the log it is saying the log4j that you are using does not work.
https://jitpack.io/com/github/pjklauser/protobuf-rpc-pro/1.1.0/build.log

Additionally when I run maven locally on my computer I get a different error:

Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project protobuf-rpc-pro-duplex: Unable to execute gpg command: Error while executing process. Cannot run program "gpg": error=2, No such file or directory -> [Help 1]

**Comment by pjklauser** [comment]
The release tag 1.1.0 was an ancient artifact migrated from google code to git. I've removed all releases - so you might be able to use Jitpack now with a kind of "snapshot".

The "maven install" doesn't work for you locally because it is trying to sign the jar (with pgp) and upload it to maven central - which only i can do from my PC. 

Why don't you take the artifacts from maven central? 
<dependency>
            <groupId>com.googlecode.protobuf-rpc-pro</groupId>
            <artifactId>protobuf-rpc-pro-duplex</artifactId>
            <version>3.3.1</version>
            <type>jar</type>
</dependency>

**Comment by dtracers** [comment]
Yeah I took it from maven central and it seemed to find it.  Thanks!

**Comment by pjklauser** [comment]
That's good to know :)
